revoke all on function public.record_demo_contact(text) from public, anon, authenticated;
grant execute on function public.record_demo_contact(text) to authenticated;
revoke all on function public.claim_pending_tenant_access() from public, anon, authenticated;
grant execute on function public.claim_pending_tenant_access() to authenticated;
revoke all on function public.operator_grant_email(uuid, text) from public, anon, authenticated;
grant execute on function public.operator_grant_email(uuid, text) to authenticated;
revoke all on function public.operator_revoke_email(uuid, text) from public, anon, authenticated;
grant execute on function public.operator_revoke_email(uuid, text) to authenticated;
revoke all on function public.operator_list_email_grants(uuid) from public, anon, authenticated;
grant execute on function public.operator_list_email_grants(uuid) to authenticated;
revoke all on function public.operator_open_demo(uuid, integer) from public, anon, authenticated;
grant execute on function public.operator_open_demo(uuid, integer) to authenticated;
revoke all on function public.operator_grant_email_by_slug(text, text) from public, anon, authenticated;
grant execute on function public.operator_grant_email_by_slug(text, text) to authenticated;
revoke all on function public.operator_revoke_email_by_slug(text, text) from public, anon, authenticated;
grant execute on function public.operator_revoke_email_by_slug(text, text) to authenticated;
revoke all on function public.get_demo_window(text) from public, anon, authenticated;
grant execute on function public.get_demo_window(text) to anon, authenticated;
revoke all on function public.submit_paid_draft(text, text, jsonb) from public, anon, authenticated;
grant execute on function public.submit_paid_draft(text, text, jsonb) to authenticated;
