/**
 * Emit `frontend/lib/tenant-map.ts` from `clients/*.json`.
 *
 * Middleware runs on the edge runtime, which has no filesystem, so it cannot use
 * the config loader. It needs host → tenant resolution to be a plain object
 * compiled into the bundle.
 *
 * Generated, never hand-edited. The generator is the only thing that knows a
 * custom domain may only appear for a `live` tenant, and hand-maintaining that
 * invariant in a second place is how a demo ends up answering on a client's
 * domain before they have paid.
 *
 *   npm run gen:tenant-map
 */

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { listClientSlugs, loadClientConfig } from '../backend/src/config/index'

type Entry = { slug: string; status: string; tier: string; template: string }

const bySubdomain: Record<string, Entry> = {}
const byCustomDomain: Record<string, Entry> = {}
const problems: string[] = []

for (const slug of listClientSlugs()) {
  const c = loadClientConfig(slug)
  const entry: Entry = { slug: c.slug, status: c.status, tier: c.tier, template: c.template }

  const sub = c.domain.demoSubdomain
  if (bySubdomain[sub]) {
    problems.push(
      `Subdomain "${sub}" is claimed by both ${bySubdomain[sub].slug} and ${c.slug}. ` +
        `One of them would silently win.`,
    )
  }
  bySubdomain[sub] = entry

  const custom = c.domain.customDomain
  if (custom) {
    // check:config already rejects this combination. Refusing again here means a
    // config edited after the last check still cannot produce a map that serves
    // an unpaid site on a real domain.
    if (c.status !== 'live') {
      problems.push(
        `${c.slug} has customDomain "${custom}" but status "${c.status}". ` +
          `A custom domain attaches only at status "live".`,
      )
      continue
    }
    const host = custom.replace(/^https?:\/\//, '').replace(/\/.*$/, '').toLowerCase()
    if (byCustomDomain[host]) {
      problems.push(`Custom domain "${host}" is claimed by both ${byCustomDomain[host].slug} and ${c.slug}.`)
    }
    byCustomDomain[host] = entry
  }
}

if (problems.length) {
  console.error(`\ngen:tenant-map failed:\n${problems.map((p) => `  - ${p}`).join('\n')}\n`)
  process.exit(1)
}

const out = `/**
 * GENERATED by \`npm run gen:tenant-map\`. Do not edit.
 *
 * Host → tenant, compiled in because middleware runs on the edge runtime and has
 * no filesystem. Regenerate after adding a client or changing a domain.
 */

export type TenantEntry = {
  slug: string
  status: 'demo' | 'sold' | 'live' | 'archived'
  tier: 't0' | 't1' | 't2' | 't3'
  template: 'editorial' | 'premium' | 'warm-contemporary' | 'bold-modern'
}

export const TENANT_MAP: {
  bySubdomain: Record<string, TenantEntry>
  byCustomDomain: Record<string, TenantEntry>
} = ${JSON.stringify({ bySubdomain, byCustomDomain }, null, 2)} as const
`

const target = join(import.meta.dirname, '..', 'frontend', 'lib', 'tenant-map.ts')
writeFileSync(target, out, 'utf8')

console.log(
  `Wrote ${target} — ${Object.keys(bySubdomain).length} subdomain(s), ` +
    `${Object.keys(byCustomDomain).length} custom domain(s)`,
)
