/**
 * Copy `NEXT_PUBLIC_*` values from the repo-root `.env` into
 * `frontend/.env.local`.
 *
 * The root `.env` is the single source for every workspace — the check
 * scripts, `test-rls.ts`, and the Next app all need the same Supabase project.
 * But Next only auto-loads `.env*` files from the directory it runs in
 * (`frontend/`), and that loading is what bakes `NEXT_PUBLIC_*` values into the
 * client bundle at build time — a value merely present in `process.env` at
 * runtime is not enough, because by then the browser bundle has already been
 * compiled without it. Bridging the two via `@next/env`'s `loadEnvConfig`
 * inside `next.config.ts` was tried first; it loads too late in Next 15's
 * TypeScript config pipeline for the substitution to happen. This sync step
 * sidesteps the timing question entirely by using the loading path Next
 * actually supports.
 *
 * Only `NEXT_PUBLIC_*` keys are copied. `SUPABASE_SERVICE_ROLE_KEY` has no
 * business anywhere near a Next app that ships a browser bundle, and copying
 * it here would be the fastest way to leak it into one.
 *
 *   npm run sync:env      — run manually, or via predev/prebuild
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = join(import.meta.dirname, '..')
const SOURCE = join(ROOT, '.env')
const TARGET = join(ROOT, 'frontend', '.env.local')

if (!existsSync(SOURCE)) {
  console.log(`No .env at repo root — nothing to sync. Copy .env.example to .env first.`)
  process.exit(0)
}

const lines = readFileSync(SOURCE, 'utf8').split('\n')
const publicLines = lines.filter((l) => l.trim().startsWith('NEXT_PUBLIC_'))

if (publicLines.length === 0) {
  console.log('No NEXT_PUBLIC_* keys found in .env. Nothing to sync.')
  process.exit(0)
}

const out =
  `# GENERATED by \`npm run sync:env\` from the repo-root .env. Do not edit directly —\n` +
  `# edit .env and re-run the sync. Gitignored.\n\n` +
  `${publicLines.join('\n')}\n`

writeFileSync(TARGET, out, 'utf8')
console.log(`Synced ${publicLines.length} NEXT_PUBLIC_* value(s) to frontend/.env.local`)
